https-portal:
  image: steveltn/https-portal
  # You can build from source code rather than use the prebuilt image from Docker Hub.
  # build: ../..
  ports:
    - 80:80
    - 443:443
    - 3000
  links:
    - bot
  # Restart https-portal on failure or after Docker host restart.
  restart: always
  environment:
    # Forward wordpress.example.com to the WordPress container.
    # You can set up multiple domains at once.
    DOMAINS: 'wordpress.example.com -> http://wordpress'
    # Using staging server by default, for there is a rate limit on production.
    # Uncomment to use Let's Encrypt production server.
    # PRODUCTION: 'true'

bot:
  image: vvkmnn/feedbackai:tag
  # deploy:
  #   replicas: 2
  #   resources:
  #     limits:
  #       cpus: "0.5"
  #       memory: 50M
  restart: on-failure
  ports:
    - "3000:3000"