version: "2"
services:
  web:
    image: vvkmnn/feedbackai:tag
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet: